# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '3f0704cb-d6e0-40b0-bfe1-85ebd5443dd4'
  
  # Web app name
  webAppName: 'thebestcloud'

  # Environment name
  environmentName: 'test-app'

  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: DockerBuild
    steps:
    - task: Docker@1
      inputs:
        containerRegistry: 'azure-registry'
        repository: 'java-app'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
